name: Auto Index URLs

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  index:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add a timeout for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the latest Python 3.x version

    - name: Verify Python version
      run: python --version

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add JSON key
      run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > indexing-index.json
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: Verify JSON key
      run: cat indexing-index.json

    - name: Run indexing script
      run: python indexing-script.py